import { Product } from './types';

// ============================================
// ZENEIO Product Catalog - 3 Categories
// Male / Female / Lingerie
// ============================================

const IMAGE_BASE = 'https://images.unsplash.com';

// --- Men's Collection ---
export const maleProducts: Product[] = [
  {
    id: 'm-001',
    slug: 'neo-vibrating-ring-pro',
    name: 'NEO Vibrating Ring Pro',
    shortDescription: 'Dual-motor precision ring for couples. 10 vibration patterns.',
    description: 'The NEO Pro redefines shared pleasure with its dual-motor system delivering 10 distinct vibration patterns simultaneously. Crafted from medical-grade silicone with a flexible yet secure fit, this ring enhances stamina while providing targeted stimulation. IPX7 waterproof design means it\'s ready anywhere.',
    price: 49.99,
    comparePrice: 69.99,
    category: 'male',
    images: [
      `${IMAGE_BASE}/photo-1607082348824-0a96f2a4b9da?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1607082349566-ec2a5a0a4b9d?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1615790440871-51d577d73f05?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 156,
    tags: ['bestseller', 'couples', 'vibrating'],
    features: [
      '10 Vibration Patterns + 5 Intensity Levels',
      'Medical-Grade Body-Safe Silicone',
      'IPX7 Waterproof - Bath & Shower Safe',
      '90-Minute Battery Life, USB Rechargeable',
      'Flexible Fit, One Size Fits Most',
      'Whisper-Quiet Motor (under 40dB)',
    ],
    specifications: {
      Material: 'Premium Silicone',
      Size: 'Flexible (fits 3-5cm diameter)',
      Weight: '45g',
      Battery: 'USB Rechargeable Li-ion',
      Runtime: '90 minutes',
      Waterproof: 'IPX7',
      Noise Level: 'under 40dB',
    },
    rating: 4.8,
    reviewCount: 342,
    isHot: true,
    isFeatured: true,
    discountPercent: 29,
    sku: 'ZNEO-MR-001',
  },
  {
    id: 'm-002',
    slug: 'apex-auto-stroker',
    name: 'APEX Auto Stroker Elite',
    shortDescription: 'AI-powered stroking device with 360° rotating sleeve.',
    description: 'Experience the future of personal pleasure with APEX Elite. Featuring AI-powered stroke analysis that learns your preferences over time, a 360° rotating textured sleeve with 7 rotation modes, and an interactive app for long-distance partner control. The heated core maintains optimal temperature throughout.',
    price: 189.99,
    comparePrice: 249.99,
    category: 'male',
    images: [
      `${IMAGE_BASE}/photo-1558618666-f8c06b85f414?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1581092160562-40aa08e78837?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1571019613454-1cb2f99b6d8b?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 89,
    tags: ['premium', 'tech', 'app-controlled'],
    features: [
      'AI-Powered Stroke Learning Technology',
      '360° Rotating Sleeve, 7 Modes',
      'Heated Core (38-42°C Adjustable)',
      'App Control + Partner Sync',
      'Real-Time Performance Analytics',
      'Premium TPE Inner Texture',
    ],
    specifications: {
      Material: 'ABS Shell + Premium TPE Sleeve',
      Dimensions: '25 x 8 cm',
      Weight: '680g',
      Battery: 'Rechargeable (2200mAh)',
      Runtime: '120 minutes max',
      Connectivity: 'Bluetooth 5.0 + App',
      Heating: '38°C-42°C adjustable',
    },
    rating: 4.9,
    reviewCount: 187,
    isNew: true,
    isFeatured: true,
    discountPercent: 24,
    sku: 'ZNEO-MS-002',
  },
  {
    id: 'm-003',
    slug: 'prostate-wand-x',
    name: 'Prostate Wand X',
    shortDescription: 'Ergonomic prostate massager with remote control.',
    description: 'Precision-engineered for P-spot stimulation, the Wand X features a curved ergonomic design that hits every time. With 12 vibration modes and a wireless remote, solo or partnered play has never been more intuitive. The warming tip adds a new dimension of sensation.',
    price: 79.99,
    comparePrice: 99.99,
    category: 'male',
    images: [
      `${IMAGE_BASE}/photo-1507003211169-0a1dd7228f2d?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1519681393784-d120267933ba?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 234,
    tags: ['prostate', 'remote', 'warming'],
    features: [
      '12 Vibration Patterns',
      'Wireless Remote (15m Range)',
      'Warming Tip Function (42°C)',
      'Ergonomic Curved Design',
      'Silent Operation (<35dB)',
      'Travel Lock Included',
    ],
    specifications: {
      Material: 'Medical-Grade Silicone',
      Insertable Length: '10cm',
      Diameter: '2.8cm',
      Battery: 'USB Rechargeable',
      Runtime: '75 minutes',
      Waterproof: 'IPX6 Splash Proof',
    },
    rating: 4.7,
    reviewCount: 215,
    discountPercent: 20,
    sku: 'ZNEO-MP-003',
  },
  {
    id: 'm-004',
    slug: 'delay-spray-premium',
    name: 'Delay Spray Premium',
    shortDescription: 'Clinically-tested desensitizing spray for lasting performance.',
    description: 'Our premium delay spray uses FDA-compliant lidocaine formula to help extend intimate sessions without sacrificing sensation entirely. Fast-acting, odorless, and safe for use with condoms. Each bottle provides up to 200 applications.',
    price: 24.99,
    category: 'male',
    images: [
      `${IMAGE_BASE}/photo-1584308666744-24acc5bfa3ad?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 500,
    tags: ['enhancement', 'spray', 'popular'],
    features: [
      'FDA-Compliant Lidocaine Formula',
      'Fast-Acting (5 minutes)',
      '200+ Applications per Bottle',
      'Condom Safe',
      'Odorless & Tasteless',
      'Discreet Packaging',
    ],
    specifications: {
      Volume: '30ml',
      Active Ingredient: 'Lidocaine 9.5%',
      Onset Time: '5 minutes',
      Duration: '30-60 minutes',
      Applications: '~200 per bottle',
    },
    rating: 4.5,
    reviewCount: 567,
    isHot: true,
    sku: 'ZNEO-MD-004',
  },
  {
    id: 'm-005',
    slug: 'sleeve-texture-master',
    name: 'Texture Master Sleeve Set',
    shortDescription: '5 interchangeable textured sleeves with suction base.',
    description: 'Five uniquely textured sleeves designed to deliver varied sensations. From ribbed to nubbed to wave-patterned interiors, swap them out based on your mood. Includes a hands-free suction cup mount for immersive solo experiences.',
    price: 59.99,
    comparePrice: 79.99,
    category: 'male',
    images: [
      `${IMAGE_BASE}//photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1523275335784-392e5a036c3f?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 178,
    tags: ['sleeve', 'variety', 'value'],
    features: [
      '5 Unique Textured Sleeves',
      'Hands-Free Suction Cup Base',
      'Easy-Clean Open Design',
      'Body-Safe TPE Material',
      'Discreet Storage Case Included',
      'Warm Water Compatible',
    ],
    specifications: {
      Material: 'Premium TPE',
      Sleeve Depth: '16cm',
      Diameter: '4cm',
      Base: 'Strong Suction Cup',
      Care: 'Warm water + toy cleaner',
    },
    rating: 4.6,
    reviewCount: 298,
    discountPercent: 25,
    isNew: true,
    sku: 'ZNEO-MT-005',
  },
];

// --- Women's Collection ---
export const femaleProducts: Product[] = [
  {
    id: 'f-001',
    slug: 'aura-wand-vibrator',
    name: 'AURA Wand Vibrator',
    shortDescription: 'Powerful wand with 20 vibration speeds & smart memory.',
    description: 'The AURA Wand delivers deep, rumbly vibrations through its flexible silicone head. With 20 speed combinations, intelligent memory recall of your last setting, and travel lock mode, it\'s the ultimate versatile pleasure tool. The ergonomic handle ensures comfort during extended use.',
    price: 69.99,
    comparePrice: 89.99,
    category: 'female',
    images: [
      `${IMAGE_BASE}/photo-1496181133206-80fc9fcfb6c9?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1464207687429-750b4d8b02cf?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1518331349616-4a0c0b5e4b92?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 267,
    tags: ['bestseller', 'wand', 'powerful'],
    features: [
      '20 Speed + Pattern Combinations',
      'Smart Memory Recall',
      'Flexible Silicone Head',
      'Travel Lock Mode',
      '180min Runtime',
      'Waterproof IPX7',
    ],
    specifications: {
      Material: 'Premium Silicone + ABS',
      Length: '29cm',
      Head Diameter: '5cm',
      Motor: 'High-Frequency Rumbly',
      Battery: 'USB Rechargeable',
      Runtime: '180 minutes',
      Noise: '<45dB',
      Waterproof: 'IPX7',
    },
    rating: 4.9,
    reviewCount: 512,
    isHot: true,
    isFeatured: true,
    discountPercent: 22,
    sku: 'ZNEO-FW-001',
  },
  {
    id: 'f-002',
    slug: 'bloom-rabbit-vibe',
    name: 'BLOOM Rabbit Vibrator',
    shortDescription: 'Dual-stimulation rabbit with thrusting shaft & rotating head.',
    description: 'BLOOM combines internal thrusting with external clitoral vibration in one elegant device. The shaft thrusts at 3 speeds while the rabbit ears provide 12 vibration modes independently controlled. The heating function brings the shaft to body temperature for ultra-realistic sensation.',
    price: 119.99,
    comparePrice: 159.99,
    category: 'female',
    images: [
      `${IMAGE_BASE}//photo-1470071459604-3b5ec3a7fe05?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1441974231531-c6227db76b6e?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1445903380105-c2b095bc1d89?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 143,
    tags: ['rabbit', 'thrusting', 'premium'],
    features: [
      '3-Speed Thrusting Shaft',
      '12-Vibration Clitoral Stimulator',
      'Heating Function (38°C)',
      'Independent Dual Controls',
      'Silent Motor System',
      'App Compatible (Optional)',
    ],
    specifications: {
      Material: 'Medical-Grade Silicone',
      Insertable Length: '11cm',
      Girth: '3.5cm',
      Thrust Depth: '1cm',
      Battery: '2200mAh Rechargeable',
      Runtime: '90 min thrusting / 150 min vibe only',
      Waterproof: 'IPX6',
    },
    rating: 4.8,
    reviewCount: 289,
    isFeatured: true,
    discountPercent: 25,
    sku: 'ZNEO-FR-002',
  },
  {
    id: 'f-003',
    slug: 'suction-rose-toy',
    name: 'SUCTION Rose Toy Pro',
    shortDescription: 'Air-pulse technology with 10 intensity levels.',
    description: 'Revolutionary air-pulse technology creates gentle suction waves that stimulate without direct contact — perfect for those who find traditional vibration too intense. The rose-shaped design is as beautiful on your nightstand as it is effective. Fully waterproof and whisper-quiet.',
    price: 44.99,
    comparePrice: 59.99,
    category: 'female',
    images: [
      `${IMAGE_BASE}/photo-1485628433970-a840bd7f1c80?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1466691202423-459386f9b10f?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 321,
    tags: ['suction', 'air-pulse', 'gentle'],
    features: [
      'Air-Pulse Suction Technology',
      '10 Intensity Levels',
      'No Direct Contact Required',
      'Whisper Quiet (<35dB)',
      '100% Waterproof',
      'Magnetic USB Charging',
    ],
    specifications: {
      Material: 'Medical-Grade Silicone',
      Size: '6.5 x 5cm',
      Weight: '65g',
      Charging: 'Magnetic USB Cable',
      Runtime: '120 minutes',
      Noise: '<35dB',
      Waterproof: 'IPX7',
    },
    rating: 4.7,
    reviewCount: 634,
    isHot: true,
    discountPercent: 25,
    sku: 'ZNEO-FS-003',
  },
  {
    id: 'f-004',
    slug: 'kegel-exercise-set',
    name: 'KEGEL Exercise Kit Pro',
    shortDescription: 'Progressive kegel balls set for pelvic floor health.',
    description: 'A complete progressive training kit featuring 3 sets of weighted kegel balls in increasing weights (25g/40g/55g). Designed by pelvic health specialists, each ball contains a smaller inner weight that creates natural kinetic movement during exercise. Improves bladder control and intensifies pleasure over time.',
    price: 39.99,
    comparePrice: 54.99,
    category: 'female',
    images: [
      `${IMAGE_BASE}/photo-1598488035139-b21b29d0bda9?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 412,
    tags: ['health', 'kegel', 'wellness'],
    features: [
      '3 Progressive Weights: 25g / 40g / 55g',
      'Inner Kinetic Weight Ball',
      'Silicone Retrieval Cord',
      'Medical-Grade Materials',
      'Exercise Guide Included',
      'Discreet Storage Bag',
    ],
    specifications: {
      Material: 'Body-Safe Silicone',
      Ball Diameter: '3.2cm / 3.5cm / 3.8cm',
      Weights: '25g, 40g, 55g',
      Cord: 'Soft Silicone Retrieval String',
      Storage: 'Velvet Pouch Included',
    },
    rating: 4.6,
    reviewCount: 198,
    discountPercent: 27,
    sku: 'ZNEO-FK-004',
  },
  {
    id: 'f-005',
    slug: 'mini-bullet-vibe',
    name: 'MINI Bullet Vibe Set',
    shortDescription: 'Pocket-sized bullet with 10 speeds, 3 color options.',
    description: 'Don\'t let its size fool you — this mini powerhouse packs surprising strength into a discreet 6cm body. Choose from 10 vibration speeds and take it anywhere. Available in Midnight Black, Rose Pink, or Ocean Blue. Perfect starter toy or travel companion.',
    price: 19.99,
    category: 'female',
    images: [
      `${IMAGE_BASE}/photo-1583394834526-1c2b4eabca44?w=600&h=600&fit=crop`,
      `${IMAGE_BASE}/photo-1557672179-7befe3e0b6d8?w=600&h=600&fit=crop`,
    ],
    inStock: true,
    stockCount: 589,
    tags: ['bullet', 'starter', 'travel'],
    features: [
      '10 Vibration Speeds',
      'Discreet Pocket Size (6cm)',
      'Single Button Control',
      '3 Color Options',
      '60+ Minute Runtime',
      'Travel Lock',
    ],
    specifications: {
      Material: 'ABS Plastic + Silicone Tip',
      Size: '6 x 1.8cm',
      Weight: '22g',
      Battery: 'AAA or USB (model varies)',
      Runtime: '60+ minutes',
      Noise: '<35dB',
    },
    rating: 4.4,
    reviewCount: 445,
    isNew: true,
    isHot: true,
    sku: 'ZNEO-FB-005',
  },
];

// --- Lingerie Collection ---
export const lingerieProducts: Product[] = [
  {
    id: 'l-001',
    slug: 'lace-babydoll-set',
    name: 'Lace Babydoll Set',
    shortDescription: 'Sheer lace babydoll with matching thong. One-size fits S-XL.',
    description: 'Exquisite French lace babydoll featuring a halter neckline, sheer bodice with floral embroidery, and flowing skirt that teases just enough. Comes with a matching lace thong. The adjustable halter straps ensure the perfect fit from S to XL. Hand-washable premium lace that feels luxurious against skin.',
    price: 34.99,
    comparePrice: 49.99,
    category: 'lingerie',
    images: [
      `${IMAGE_BASE}//photo-1515886657613-9f3515b0c78f?w=600&h=800&fit=crop`,
      `${IMAGE_BASE}/photo-1518310381062-cd2b1e9bb0b7?w=600&h=800&fit=crop`,
      `${IMAGE_BASE}//photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop`,
    ],
    inStock: true,
    stockCount: 245,
    tags: ['lace', 'babydoll', 'bestseller'],
    features: [
      'French Chantilly Lace',
      'Halter Neckline with Tie Closure',
      'Floral Embroidery Detail',
      'Matching Lace Thong Included',
      'Fits Sizes S-XL (One Size)',
      'Hand-Wash Recommended',
    ],
    specifications: {
      Material: '90% Nylon, 10% Spandex Lace',
      Style: 'Halter Babydoll + Thong Set',
      Fit: 'S, M, L, XL (Adjustable)',
      Closure: 'Halter tie back',
      Care: 'Hand wash cold, line dry',
    },
    rating: 4.8,
    reviewCount: 367,
    isHot: true,
    isFeatured: true,
    discountPercent: 30,
    sku: 'ZNEO-LB-001',
  },
  {
    id: 'l-002',
    slug: 'body-stockings-set',
    name: 'Sensual Bodystocking Set',
    shortDescription: 'Full-body fishnet stocking with crotchless design.',
    description: 'Make a bold statement with this full-body fishnet bodysuit. The diamond pattern netting creates a stunning visual effect while the crotchless design adds accessibility. Features a high neckline, long sleeves, and foot coverage for total-body allure. Stretchy enough for comfortable wear during extended play.',
    price: 24.99,
    comparePrice: 39.99,
    category: 'lingerie',
    images: [
      `${IMAGE_BASE}/photo-1509631179647-0177331693ae?w=600&h=800&fit=crop`,
      `${IMAGE_BASE}/photo-1515372039744-b8f02b3174af?w=600&h=800&fit=crop`,
    ],
    inStock: true,
    stockCount: 178,
    tags: ['stockings', 'fishnet', 'bold'],
    features: [
      'Full-Body Coverage',
      'Diamond Fishnet Pattern',
      'Crotchless Design',
      'High Neckline + Long Sleeves',
      'Foot Coverage',
      'One Size (Stretches to fit most)',
    ],
    specifications: {
      Material: '90% Nylon, 10% Spandex',
      Pattern: 'Diamond Net (Medium Gauge)',
      Coverage: 'Full body (neck to toe)',
      Fit: 'One Size (up to US 14)',
      Stretch: '4-way stretch fabric',
    },
    rating: 4.6,
    reviewCount: 213,
    discountPercent: 38,
    sku: 'ZNEO-LS-002',
  },
  {
    id: 'l-003',
    slug: 'satin-robe-set',
    name: 'Satin Robe & Chemise Set',
    shortDescription: 'Luxurious satin robe over delicate chemise.',
    description: 'Indulge in luxury with this two-piece set featuring a knee-length satin robe with belt and a matching spaghetti-strap chemise underneath. The robe has a subtle sheen that catches light beautifully, while the chemise offers a glimpse of what lies beneath. Perfect for bridal gifts or anniversary surprises.',
    price: 54.99,
    comparePrice: 74.99,
    category: 'lingerie',
    images: [
      `${IMAGE_BASE}/photo-1551029029-823b3cac1cfd?w=600&h=800&fit=crop`,
      `${IMAGE_BASE}/photo-1558618666-f8c06b85f414?w=600&h=800&fit=crop`,
    ],
    inStock: true,
    stockCount: 134,
    tags: ['robe', 'satin', 'luxury'],
    features: [
      'Knee-Length Satin Robe',
      'Matching Belted Waist',
      'Spaghetti Strap Chemise',
      'Lace Trim Detail',
      'Available in 3 Colors',
      'Gift Box Packaging',
    ],
    specifications: {
      Material: 'Robe: 100% Polyester Satin; Chemise: Nylon/Lace blend',
      Robe Length: 'Knee length (~90cm)',
      Colors: 'Midnight Black / Wine Red / Champagne Gold',
      Sizes: 'S / M / L / XL',
      Closure: 'Self-tie sash belt',
      Care: 'Dry clean recommended',
    },
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    discountPercent: 27,
    sku: 'ZNEO-LR-003',
  },
  {
    id: 'l-004',
    slug: 'leather-harness-set',
    name: 'Leather Harness Lingerie',
    shortDescription: 'Edgy leather strappy harness with cut-out details.',
    description: 'For those who dare, this leather harness lingerie set commands attention. Crafted from vegan-friendly faux leather with strategic cut-outs and adjustable straps throughout. The strappy cage design reveals skin in all the right places. Metal hardware details add industrial-chic finishing touches.',
    price: 44.99,
    comparePrice: 64.99,
    category: 'lingerie',
    images: [
      `${IMAGE_BASE}/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop`,
      `${IMAGE_BASE}/photo-1517841905440-9492ea7dc07f?w=600&h=800&fit=crop`,
    ],
    inStock: true,
    stockCount: 98,
    tags: ['leather', 'edgy', 'harness'],
    features: [
      'Vegan Faux Leather',
      'Cage/Cut-Out Design',
      'Fully Adjustable Straps',
      'Metal O-Ring Hardware',
      'High-Waist Panty Included',
      'Statement Piece',
    ],
    specifications: {
      Material: 'PU Vegan Leather + Elastic Straps',
      Style: 'Strappy Cage Top + High-Waist Bottom',
      Adjustability: 'Multiple points',
      Hardware: 'Antique gold-tone metal rings/buckles',
      Fit: 'S / M / L',
      Care: 'Spot clean only',
    },
    rating: 4.7,
    reviewCount: 142,
    isNew: true,
    discountPercent: 31,
    sku: 'ZNEO-LH-004',
  },
  {
    id: 'l-005',
    slug: 'lace-garter-belt-set',
    name: 'Lace Garter Belt & Bra Set',
    shortDescription: 'Classic garter belt set with underwire bra & stockings.',
    description: 'Timeless seduction reimagined. This set includes a balconette-style underwire bra with lace cups, a matching garter belt with 4 clips, and a pair of thigh-high sheer stockings. The scalloped lace trim adds feminine elegance while the structured bra provides support. A classic for good reason.',
    price: 42.99,
    comparePrice: 59.99,
    category: 'lingerie',
    images: [
      `${IMAGE_BASE}/photo-1490481651871-ab68de25d43d?w=600&h=800&fit=crop`,
      `${IMAGE_BASE}/photo-1501386761578-eae7c8cdaa93?w=600&h=800&fit=crop`,
    ],
    inStock: true,
    stockCount: 167,
    tags: ['garter', 'classic', 'lace'],
    features: [
      'Underwire Balconette Bra',
      'Matching Garter Belt (4 Clips)',
      'Thigh-High Sheer Stockings',
      'Scalloped Lace Trim',
      'Hook-and-Eye Back Closure',
      'Sizes B-D Cup',
    ],
    specifications: {
      Material: 'Lace + Mesh + Elastane blend',
      Bra Style: 'Balconette underwire',
      Garter: '4-clip adjustable',
      Stockings: 'Sheer 15D, back-seam detail',
      Sizes: '32B-36D (US sizing)',
      Colors: 'Black / White / Red',
      Care: 'Hand wash, line dry',
    },
    rating: 4.8,
    reviewCount: 201,
    discountPercent: 28,
    isHot: true,
    sku: 'ZNEO-LG-005',
  },
];

// --- All Products Combined ---
export const ALL_PRODUCTS: Product[] = [...maleProducts, ...femaleProducts, ...lingerieProducts];

// --- Helper Functions ---
export function getProductsByCategory(category: string): Product[] {
  return ALL_PRODUCTS.filter(p => p.category === category);
}

export function getProductBySlug(slug: string): Product | undefined {
  return ALL_PRODUCTS.find(p => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find(p => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return ALL_PRODUCTS.filter(p => p.isFeatured);
}

export function getNewProducts(): Product[] {
  return ALL_PRODUCTS.filter(p => p.isNew);
}

export function getHotProducts(): Product[] {
  return ALL_PRODUCTS.filter(p => p.isHot);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return ALL_PRODUCTS.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.description.toLowerCase().includes(q) ||
    p.tags?.some(t => t.toLowerCase().includes(q)) ||
    p.category.includes(q)
  );
}

export function formatPrice(price: number): string {
  return `$${price.toFixed(2)}`;
}
